### ISSUE TITLE
network policies for jupyter

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/iac-flux-jupyter#16]
As architect, we would like a clearly defined network policy for jupyter and associated containers to prevent access to unexpected locations on the internet, so that users cannot easily send data outside of the environment

@vvcb Could you confirm whether the jupyter containers need any visibility of the public internet? if so which sites should be allowed?

**Comment by vvcb** [comment]
@qcaas-nhs-sjt , this appears to be a duplicate of #9 .

**Comment by qcaas-nhs-sjt** [comment]
@vvcb yes, i'll close this one off
