### ISSUE TITLE
Internal server error (Status code 500) when accessing hub

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-jupyter#17]
When accessing the spawn page of JupyterHub (where the workspaces should be listed, https://jupyter.xlscsde.nhs.uk/hub/spawn/), user is presented with a 500: Internal server error message. 

This disappears when I logout and login again. K8s logs suggest that this is due the keycloak token expiring and the custom config.py script throwing an unhandled exception when trying to retrieve workspace details for the current user.

![image](https://github.com/lsc-sde/iac-flux-jupyter/assets/8311806/69cb6ac3-b41f-444a-bb29-8cf8275dfd87)

## Expected behaviour:

If a user has authenticated already, then the spawn page should display the workspaces/profiles available for that user.

If we are expecting the user to login again after a period of inactivity, then the user should be returned to the login page.

In either case, the exception should be handled internally and the user presented with a more useful message and next steps.

**Comment by qcaas-nhs-sjt** [comment]
This issue was related to keycloak implementation of the kubespawner custom script and no longer applies
