### ISSUE TITLE
Get Basic Jupyterhub Template working

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/iac-flux-jupyter#6]
Create a no frills but working implementation of jupyterhub

**Comment by vvcb** [comment]
Closed by [d616b0b](https://github.com/lsc-sde/iac-flux-jupyter/commit/d616b0bd91c50f138858de456a5a92006399a16a).

**Comment by qcaas-nhs-sjt** [comment]
@vvcb Not going to make a habit of working at the weekend but I wanted to sort this one issue. So I've sorted out the issue with the pvc's and you can now login to the jupyterhub on the sandbox environment from the jump box

https://sandbox-jupyterhub.privatelink.uksouth.azmk8s.io/hub/login
