### ISSUE TITLE
Provisioning PVC/PV specific to each project workspace

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-jupyter#8]
In the old TRE, Azure File Shares were created manually and researcher data was uploaded into these. PVC/PV corresponding to these shares were then created on the cluster using `kubectl` and yaml manifests and the name of the PVC was included in workspace.yaml files. 

The custom config script looks for this in the storage account and mounts this share using  `KubeSpawner.modify_pod_hook`. The pod does not deploy if the expected PVC/PV cannot be found. All workspaces also got a common, read-only share with generic documentation.

This entire workflow of creating and managing project specific storage needs to be re-engineered following discussion here in this issue.

**Comment by qcaas-nhs-sjt** [comment]
This has been implemented with #15 @vvcb please review
